// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:developer';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE9PCGkbRM5cICVnnSRpyc4zaN7wh6hW0',
    appId: '1:667088675795:android:b8909556bd1776e1d78526',
    messagingSenderId: '667088675795',
    projectId: 'notee-f7e62',
    storageBucket: 'notee-f7e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpul_hXJRs56WLlQAxp8-YYR2xKyhfJI',
    appId: '1:667088675795:ios:08d59a5d49db2a84d78526',
    messagingSenderId: '667088675795',
    projectId: 'notee-f7e62',
    storageBucket: 'notee-f7e62.appspot.com',
    iosBundleId: 'com.AppsAndMore.Training',
  );
}

class PushNotification {
  static FirebaseMessaging messaging = FirebaseMessaging.instance;

  static Future initialise() async {
    await messaging.requestPermission();
    String? fcmToken = await messaging.getToken();
    log(fcmToken ?? "null");
  }
}
